name: Test on PR branch
on: pull_request

jobs:
  test-on-pr-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Build compas-open
        working-directory: ./components/compas-open
        run: npm run build

      - name: Run tests for compas-open
        working-directory: ./components/compas-open
        run: npm run-script test

      - name: Run tests for compas-open-plugin
        working-directory: ./packages/compas-open-plugin
        run: npm run-script test
